version: "3"

services:
  mail_postgress:
    image: "postgres:13"
    container_name: mail_postgress
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5432:5432"
    logging:
     driver: "json-file"
     options:
       max-size: "100m"