"""add autoincrement

Revision ID: e5b8c54133db
Revises: 8b5db94b023e
Create Date: 2023-02-17 14:10:31.313545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e5b8c54133db"
down_revision = "8b5db94b023e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
