"""add targets and actions

Revision ID: 7a1f810f8e08
Revises: 5a077a981eb0
Create Date: 2023-02-26 16:48:23.340692

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a1f810f8e08"
down_revision = "5a077a981eb0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
    INSERT INTO permission_targets (id, name, human_name, created_at)
    VALUES
    (DEFAULT, 'DOMAIN'::targetsenum, 'Домены', (SELECT CURRENT_TIMESTAMP)),
    (DEFAULT, 'USER'::targetsenum, 'Пользователи', (SELECT CURRENT_TIMESTAMP)),
    (DEFAULT, 'PERMISSION'::targetsenum, 'Пермишены', (SELECT CURRENT_TIMESTAMP)),
    (DEFAULT, 'TARGET'::targetsenum, 'Таргеты', (SELECT CURRENT_TIMESTAMP)),
    (DEFAULT, 'ROLE'::targetsenum, 'Роли', (SELECT CURRENT_TIMESTAMP));
    """
    )
    op.execute(
        """
        INSERT INTO permission_actions (id, name, human_name, created_at)
        VALUES
        (DEFAULT, 'CREATE'::actionsenum, 'Создание', (SELECT CURRENT_TIMESTAMP)),
        (DEFAULT, 'READ'::actionsenum, 'Просмотр', (SELECT CURRENT_TIMESTAMP)),
        (DEFAULT, 'UPDATE'::actionsenum, 'Редактирование', (SELECT CURRENT_TIMESTAMP)),
        (DEFAULT, 'DELETE'::actionsenum, 'Удаление', (SELECT CURRENT_TIMESTAMP));
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"TRUNCATE permission_actions CASCADE")
    op.execute(f"TRUNCATE permission_targets CASCADE")
    # ### end Alembic commands ###
