"""add permissions and roles

Revision ID: 3d7cb607c71d
Revises: 8ae6a63cb950
Create Date: 2023-02-26 16:20:48.460764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3d7cb607c71d"
down_revision = "8ae6a63cb950"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission_actions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("human_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_permission_actions_id"), "permission_actions", ["id"], unique=False)
    op.create_table(
        "permission_targets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("human_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_permission_targets_id"), "permission_targets", ["id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("human_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_table(
        "permission_target_actions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("target", sa.Integer(), nullable=False),
        sa.Column("actions", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["actions"], ["permission_actions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target"], ["permission_targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_permission_target_actions_id"),
        "permission_target_actions",
        ["id"],
        unique=False,
    )
    op.create_table(
        "roles_target_actions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role", sa.Integer(), nullable=False),
        sa.Column("target_action", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["role"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["target_action"], ["permission_target_actions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_roles_target_actions_id"), "roles_target_actions", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_roles_target_actions_id"), table_name="roles_target_actions")
    op.drop_table("roles_target_actions")
    op.drop_index(op.f("ix_permission_target_actions_id"), table_name="permission_target_actions")
    op.drop_table("permission_target_actions")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permission_targets_id"), table_name="permission_targets")
    op.drop_table("permission_targets")
    op.drop_index(op.f("ix_permission_actions_id"), table_name="permission_actions")
    op.drop_table("permission_actions")
    # ### end Alembic commands ###
