"""chang_fk

Revision ID: 36d47f6f080b
Revises: 6a3fef76d937
Create Date: 2023-02-17 22:56:01.423313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36d47f6f080b"
down_revision = "6a3fef76d937"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("domainmodel", "owner_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("domainmodel", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
