"""unique constraint

Revision ID: 33f451a113c1
Revises: 4b80d0b27bc6
Create Date: 2023-03-03 13:59:43.783131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "33f451a113c1"
down_revision = "4b80d0b27bc6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "permission_target_actions", ["target_id", "action_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "permission_target_actions", type_="unique")
    # ### end Alembic commands ###
