"""remove enum from db

Revision ID: 4b80d0b27bc6
Revises: 8435cade4fdd
Create Date: 2023-03-03 13:46:45.874955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4b80d0b27bc6"
down_revision = "8435cade4fdd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "permission_actions",
        "name",
        existing_type=postgresql.ENUM("CREATE", "READ", "UPDATE", "DELETE", name="actionsenum"),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "permission_targets",
        "name",
        existing_type=postgresql.ENUM(
            "DOMAIN", "USER", "PERMISSION", "TARGET", "ROLE", name="targetsenum"
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "permission_targets",
        "name",
        existing_type=sa.String(),
        type_=postgresql.ENUM("DOMAIN", "USER", "PERMISSION", "TARGET", "ROLE", name="targetsenum"),
        existing_nullable=False,
    )
    op.alter_column(
        "permission_actions",
        "name",
        existing_type=sa.String(),
        type_=postgresql.ENUM("CREATE", "READ", "UPDATE", "DELETE", name="actionsenum"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
