"""add autoincrement users

Revision ID: 4cb5669a364e
Revises: e5b8c54133db
Create Date: 2023-02-17 14:11:14.979424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4cb5669a364e"
down_revision = "e5b8c54133db"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
