"""add domains

Revision ID: 64858ec81fe3
Revises: 4cb5669a364e
Create Date: 2023-02-17 17:32:48.050305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "64858ec81fe3"
down_revision = "4cb5669a364e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
