"""rename table

Revision ID: 8ae6a63cb950
Revises: 36d47f6f080b
Create Date: 2023-02-18 14:21:58.356853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8ae6a63cb950"
down_revision = "36d47f6f080b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domains",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_domains_id"), "domains", ["id"], unique=False)
    op.drop_index("ix_domainmodel_id", table_name="domainmodel")
    op.drop_table("domainmodel")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domainmodel",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name="domainmodel_owner_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="domainmodel_pkey"),
        sa.UniqueConstraint("name", name="domainmodel_name_key"),
    )
    op.create_index("ix_domainmodel_id", "domainmodel", ["id"], unique=False)
    op.drop_index(op.f("ix_domains_id"), table_name="domains")
    op.drop_table("domains")
    # ### end Alembic commands ###
