"""rename columns

Revision ID: 8435cade4fdd
Revises: 7a1f810f8e08
Create Date: 2023-02-26 23:54:47.542102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8435cade4fdd"
down_revision = "7a1f810f8e08"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permission_target_actions",
        sa.Column("target_id", sa.Integer(), nullable=False),
    )
    op.add_column(
        "permission_target_actions",
        sa.Column("action_id", sa.Integer(), nullable=False),
    )
    op.drop_constraint(
        "permission_target_actions_actions_fkey",
        "permission_target_actions",
        type_="foreignkey",
    )
    op.drop_constraint(
        "permission_target_actions_target_fkey",
        "permission_target_actions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "permission_target_actions",
        "permission_targets",
        ["target_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "permission_target_actions",
        "permission_actions",
        ["action_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("permission_target_actions", "actions")
    op.drop_column("permission_target_actions", "target")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permission_target_actions",
        sa.Column("target", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "permission_target_actions",
        sa.Column("actions", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "permission_target_actions_target_fkey",
        "permission_target_actions",
        "permission_targets",
        ["target"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "permission_target_actions_actions_fkey",
        "permission_target_actions",
        "permission_actions",
        ["actions"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("permission_target_actions", "action_id")
    op.drop_column("permission_target_actions", "target_id")
    # ### end Alembic commands ###
